/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured databases */
        get: operations["list-databases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{id}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger on-demand backup for a database */
        post: operations["trigger-database-backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{id}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List backup files in storage destinations for a database */
        get: operations["list-database-backups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a database from a storage destination backup */
        post: operations["restore-database-backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured backup destinations */
        get: operations["list-destinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get backup run history */
        get: operations["get-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run execution details and logs */
        get: operations["get-run-detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run execution output logs */
        get: operations["get-run-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overall backup statistics */
        get: operations["get-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daemon status */
        get: operations["get-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DatabaseInfo: {
            /** @example app_db */
            database: string;
            /**
             * @example [
             *       "local_storage",
             *       "offsite_s3"
             *     ]
             */
            destinations: string[] | null;
            /** @example postgres */
            engine: string;
            /** @example pg-cluster.internal */
            host: string;
            /** @example false */
            is_running: boolean;
            last_run?: components["schemas"]["Run"];
            /** @example production_pg */
            name: string;
            /** Format: date-time */
            next_run_at?: string;
            /**
             * Format: int64
             * @example 5432
             */
            port: number;
            /** @example 0 *\/6 * * * */
            schedule: string;
        };
        DestinationInfo: {
            /** @example company-backups */
            bucket?: string;
            /** @example true */
            encrypted: boolean;
            /** @example s3.amazonaws.com */
            endpoint?: string;
            /** @example offsite_s3 */
            name: string;
            /** @example backups/{{ .Database }}.enc */
            path: string;
            retention?: components["schemas"]["RetentionPolicy"];
            /** @example s3 */
            type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HistoryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryOutputBody.json
             */
            readonly $schema?: string;
            runs: components["schemas"]["Run"][] | null;
            /** Format: int64 */
            total: number;
        };
        ListBackupsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListBackupsOutputBody.json
             */
            readonly $schema?: string;
            backups: components["schemas"]["StorageBackupItem"][] | null;
        };
        RestoreBackupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RestoreBackupInputBody.json
             */
            readonly $schema?: string;
            /** @description Path of backup file in destination */
            backup_path: string;
            /** @description Name of storage destination */
            destination: string;
        };
        RestoreBackupOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RestoreBackupOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @example 1250
             */
            duration_ms: number;
            logs?: string;
            /** @example Database dev_db restored successfully */
            message: string;
        };
        RetentionPolicy: {
            /** Format: int64 */
            daily: number;
            /** Format: int64 */
            hourly: number;
            /** Format: int64 */
            keep_last: number;
            /** Format: int64 */
            monthly: number;
            /** Format: int64 */
            weekly: number;
            /** Format: int64 */
            yearly: number;
        };
        Run: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Run.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            completed_at?: string;
            database_name: string;
            destinations: string[] | null;
            /** Format: int64 */
            duration_ms: number;
            engine: string;
            error_message?: string;
            id: string;
            logs?: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            started_at: string;
            status: string;
        };
        RunLogsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RunLogsOutputBody.json
             */
            readonly $schema?: string;
            /** @example run-123 */
            id: string;
            /** @example [2026-09-14T00:00:00Z] Backup started... */
            logs: string;
        };
        StatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Total configured databases
             * @example 5
             */
            database_count: number;
            /**
             * Format: int64
             * @description Total configured storage destinations
             * @example 2
             */
            destination_count: number;
            /**
             * @description Overall system health
             * @example healthy
             */
            status: string;
            /**
             * Format: int64
             * @description Daemon uptime in seconds
             * @example 3600
             */
            uptime_seconds: number;
            /**
             * @description arkbase version
             * @example 1.0.0
             */
            version: string;
        };
        StorageBackupItem: {
            database: string;
            destination: string;
            destination_type: string;
            encrypted: boolean;
            filename: string;
            /** Format: date-time */
            mod_time: string;
            path: string;
            /** Format: int64 */
            size_bytes: number;
        };
        SummaryStats: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SummaryStats.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            failed_count: number;
            /** Format: date-time */
            last_backup_at?: string;
            /** Format: int64 */
            successful_count: number;
            /** Format: int64 */
            total_backups: number;
            /** Format: int64 */
            total_databases: number;
            /** Format: int64 */
            total_size_bytes: number;
        };
        TriggerBackupOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TriggerBackupOutputBody.json
             */
            readonly $schema?: string;
            /** @example Backup triggered */
            message: string;
            run_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseInfo"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "trigger-database-backup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Name of the database to backup */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerBackupOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-database-backups": {
        parameters: {
            query?: {
                /** @description Optional filter by storage destination name */
                destination?: string;
            };
            header?: never;
            path: {
                /** @description Name of the database */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBackupsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "restore-database-backup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Name of the database to restore */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreBackupInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreBackupOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationInfo"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-history": {
        parameters: {
            query?: {
                /** @description Number of records to return */
                limit?: number;
                /** @description Offset for pagination */
                offset?: number;
                /** @description Filter by database name */
                database?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-run-detail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-run-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLogsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryStats"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
